name : Hello World # The name of the workflow

on: [push] # the event that triggers the workflow. In this case, the workflow is triggered when the code is pushed to the repository

jobs:
  build:
    runs-on: ubuntu-latest # The operating system environement that the job runs on. In this case, runs on the latest version of ubuntu

    steps:
      - name: Say Hello # The name of the step, it is just for reability
        run: echo ${{secrets.DOCKER_USERNAME}} #'Hello, world!'