name : Hello World # The name of the workflow

on: [push] # the event that triggers the workflow. In this case, the workflow is triggered when the code is pushed to the repository

jobs:
  build:
    runs-on: ubuntu-latest # The operating system environement that the job runs on. In this case, runs on the latest version of ubuntu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Docker Username
      run: echo $DOCKER_USERNAME
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}